# -*- coding: utf-8 -*-
"""01.FrecuenciaDeAcceso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6MjrBefWq18s1zAXQn-tNz2l-GJ-vZi

## Importar librerías y JSON
"""

import json
import pandas as pd

path = "/content/logs_KX7A_20260220-1944_GrupoB.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

"""## Arreglar formato"""

# arreglar anidamiento doble
if isinstance(data, list) and len(data) == 1 and isinstance(data[0], list):
    records = data[0]
else:
    records = data

df = pd.json_normalize(records)

df.head()

"""### Convertir formato de fecha"""

df["hora"] = pd.to_datetime(
    df["hora"],
    format="%d/%m/%y, %H:%M:%S",
    errors="coerce"
)

"""## Extraer fechas"""

df["fecha"] = df["hora"].dt.date

daily_frequency = (
    df.groupby(
        ["fecha", "nombrecompletodelusuario", "nombredelevento"]
    )
    .size()
    .reset_index(name="frecuencia")
)

daily_frequency.head()

"""## Formato legible (Usuario - Eventos)"""

pivot_frequency = daily_frequency.pivot_table(
    index=["fecha", "nombrecompletodelusuario"],
    columns="nombredelevento",
    values="frecuencia",
    fill_value=0
).reset_index()

pivot_frequency.head(200)

# Crear pivot
pivot_frequency = daily_frequency.pivot_table(
    index=["fecha", "nombrecompletodelusuario"],
    columns="nombredelevento",
    values="frecuencia",
    fill_value=0
).reset_index()

pivot_frequency.columns.name = None

"""## Exportar a excel"""

pivot_frequency.to_excel("daily_frequency_pivot.xlsx", index=False)

"""## Opciones display"""

## mostrar tamaño del JSON
df.shape

df

"""## Exportar"""

# Export a Excel
daily_frequency.to_excel("daily_frequency.xlsx", index=False)