# -*- coding: utf-8 -*-
"""05. Latencia de repuesta a menciones/tareas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q08EkgAZQu7W678ULG3CHx79oZiLQTic
"""

import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()
from sklearn.linear_model import LinearRegression

df = pd.read_excel('/content/logs_KX7A_20260212-1051 - Copy.xlsx')

eventos_ver = [
    'Módulo de curso visto',
    'El estado del envío ha sido visto.',
    'Formato de envío visto.'
]

eventos_responder = [
    'Se ha enviado un envío',
    'Envio creado.'
]

df_ver = df[df['Nombre del evento'].isin(eventos_ver)]
df_resp = df[df['Nombre del evento'].isin(eventos_responder)]

df_ver = df_ver[['Nombre completo del usuario','Contexto del evento','Hora']]
df_ver = df_ver.rename(columns={'Hora':'Hora_ver'})

df_resp = df_resp[['Nombre completo del usuario','Contexto del evento','Hora']]
df_resp = df_resp.rename(columns={'Hora':'Hora_resp'})

df_ver = df_ver[['Nombre completo del usuario','Contexto del evento','Hora']]
df_ver = df_ver.rename(columns={'Hora':'Hora_ver'})

df_resp = df_resp[['Nombre completo del usuario','Contexto del evento','Hora']]
df_resp = df_resp.rename(columns={'Hora':'Hora_resp'})

lat['Hora_resp'] = pd.to_datetime(lat['Hora_resp'], format='%d/%m/%y, %H:%M:%S')
lat['Hora_ver'] = pd.to_datetime(lat['Hora_ver'], format='%d/%m/%y, %H:%M:%S')
lat['latencia_horas'] = (
    lat['Hora_resp'] - lat['Hora_ver']
).dt.total_seconds() / 3600

lat = lat[lat['latencia_horas'] >= 0]

lat_usuario = lat.groupby('Nombre completo del usuario')['latencia_horas'].agg([
    'mean',
    'std',
    'count'
]).reset_index()

lat_usuario.columns = [
    'Usuario',
    'latency_mean',
    'latency_std',
    'response_count'
]

lat_usuario['latency_cv'] = (
    lat_usuario['latency_std'] /
    lat_usuario['latency_mean']
)

def clasificar_participacion(mean, cv):

    if mean > 72:        # más de 3 días
        return 2         # Demora prolongada
    elif mean < 1 and cv < 0.25:
        return 2         # Hiper-respuesta
    elif cv < 0.5:
        return 0         # Latencia similar
    else:
        return 1         # Variaciones ocasionales

lat_usuario['participacion_social'] = lat_usuario.apply(
    lambda x: clasificar_participacion(
        x['latency_mean'],
        x['latency_cv']
    ),
    axis=1
)

lat_usuario.head()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

lat_usuario[['mean_norm','cv_norm']] = scaler.fit_transform(
    lat_usuario[['latency_mean','latency_cv']]
)

lat_usuario['riesgo_score'] = (
    lat_usuario['mean_norm'] * 0.6 +
    lat_usuario['cv_norm'] * 0.4
)

top_10_peor = lat_usuario.sort_values(
    by='riesgo_score',
    ascending=False
).head(10)

top_10_peor

top_10_mejor = lat_usuario.sort_values(
    by='riesgo_score'
).head(10)

top_10_mejor