# -*- coding: utf-8 -*-
"""06.BusquedaDeApoyo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e93bIkOyQGQe2-lKU6Skxa9tQGZwMESI
"""

import json
import pandas as pd

path = "/content/logs_KX7A_20260220-1944_GrupoB.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

"""Arreglar formato"""

if isinstance(data, list) and len(data) == 1 and isinstance(data[0], list):
    records = data[0]
else:
    records = data

df = pd.json_normalize(records)

df.head()

df["nombredelevento"].unique()

apoyo = df[
    df["nombredelevento"].str.contains(
        "Comentario creado|Módulo de curso visto|Formato de envío visto|Reporte de usuario de curso visto",
        case=False,
        na=False
    )
]

busqueda_apoyo = apoyo.groupby(
    "nombrecompletodelusuario"
).size().reset_index(name="BusquedaApoyo")

busqueda_apoyo

busqueda_apoyo.to_json(
    "/content/indicador_entrega_tareas.json",
    orient="records",
    force_ascii=False,
    indent=2
)

print("Archivo JSON guardado correctamente")