# -*- coding: utf-8 -*-
"""07.EntregaDeTareas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGcPVaI6EjHMGXDKdY5c4aCLLqTweb7L
"""

import json
import pandas as pd

path = "/content/logs_KX7A_20260220-1944_GrupoB.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, list) and len(data) == 1 and isinstance(data[0], list):
    records = data[0]
else:
    records = data

df = pd.json_normalize(records)

df.head()

# 3. LIMPIAR NOMBRES DE COLUMNAS
# ================================
df.columns = df.columns.str.strip()

# ================================
# 4. FILTRAR EVENTOS DE TAREAS
# ================================
tareas = df[
    df["nombredelevento"].str.contains(
        "Envío creado|Se ha enviado un envío",
        case=False,
        na=False
    )
]

# ================================
# 5. INDICADOR (CONTEO)
# ================================
entregas = tareas.groupby(
    "nombrecompletodelusuario"
).size().reset_index(name="EntregaTareas")


resultado_final_filtrado = resultado_final[
    ["nombrecompletodelusuario", "EntregaTareas"]
]

# ================================
# 9. GUARDAR COMO JSON
# ================================
resultado_final_filtrado.to_json(
    "/content/indicador_entrega_tareas.json",
    orient="records",
    force_ascii=False,
    indent=3
)

print("Archivo JSON guardado correctamente")