# -*- coding: utf-8 -*-
"""08.ConductaEnEvaluaciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtonkqOXdPXfS3i3mFSnYdDchO3j2Tc9
"""

import json
import pandas as pd

path = "/content/logs_KX7A_20260220-1944_GrupoB.json"

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, list) and len(data) == 1 and isinstance(data[0], list):
    records = data[0]
else:
    records = data

df = pd.json_normalize(records)

df.head()

col_evento = "nombredelevento"
col_contexto = "contextodelevento"
col_usuario = "nombrecompletodelusuario"

# --- 3. FILTRAR SOLO EVALUACIONES (MUY IMPORTANTE) ---
evaluaciones = df[
    df[col_contexto].str.contains("Tarea: Examen T-Oportunidad|Tarea: Examen Grupo B-1|Tarea: Examen Grupo B-2|Tarea: Examen Grupo B-3|Tarea: Examen Grupo B-4|Tarea: Examen Grupo B-5|Tarea: Examen Parcial 2 SO|Tarea: Examen SO U2|Tarea: Éxamen SO Unidad 1-B |Tarea:Examen Unidad 2 Grupo A|Tarea:Examen Unidad 2 Grupo B",
                                  case=False, na=False)
]

# --- 4. CLASIFICAR EVENTOS ---

# Inicio de examen
inicio = evaluaciones[
    evaluaciones[col_evento].str.contains("intento|started|El usuario a guardado un envío|Envío creado.", case=False, na=False)
]

# Interacción dentro del examen
interaccion = evaluaciones[
    evaluaciones[col_evento].str.contains("vista|view|pregunta|answer|Módulo de curso visto", case=False, na=False)
]

# Finalización del examen
fin = evaluaciones[
    evaluaciones[col_evento].str.contains("enviado|submit|finalizado|Se ha enviado un envío", case=False, na=False)
]

# --- 5. CONTAR POR USUARIO ---
inicio_count = inicio.groupby(col_usuario).size()
interaccion_count = interaccion.groupby(col_usuario).size()
fin_count = fin.groupby(col_usuario).size()

# --- 6. UNIR RESULTADOS ---
conducta = pd.DataFrame({
    "inicio": inicio_count,
    "interaccion": interaccion_count,
    "fin": fin_count
}).fillna(0)

# --- 7. CALCULAR INDICADOR ---
conducta["conducta_evaluaciones"] = (
    conducta["fin"] * 0.5 +
    conducta["interaccion"] * 0.3 +
    conducta["inicio"] * 0.2
)

# --- 9. RESETEAR ÍNDICE PARA JSON ---
conducta = conducta.reset_index()

# --- 10. EXPORTAR A JSON ---
conducta.to_json(
    "/content/indicador_conducta_evaluaciones.json",
    orient="records",
    force_ascii=False,
    indent=3
)

print("✅ Indicador generado y guardado correctamente")