# -*- coding: utf-8 -*-
"""Calidad/longitud de entregas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yST8rXB7KaB8fiMC1E0ykFMoPhRcZSFK
"""

import json
import pandas as pd
import re

# Subir archivos si estás en Colab
from google.colab import files
uploaded = files.upload()

with open("rubrics (1).json", "r", encoding="utf-8") as f:
    rubrics = json.load(f)

with open("grades_with_user_random (1).json", "r", encoding="utf-8") as f:
    grades = json.load(f)

def limpiar_texto(texto):
    if not texto:
        return ""
    texto = re.sub(r"<.*?>", "", texto)
    texto = texto.replace("\r\n", " ").replace("\n", " ")
    return " ".join(texto.split())


def rubrics_summary(rubrics_json):
    rows = []

    if isinstance(rubrics_json, dict):
        rubrics_json = [rubrics_json]

    for item in rubrics_json:
        rubric_data = item.get("rubric", {})

        for area in rubric_data.get("areas", []):
            for definition in area.get("definitions", []):
                rubric_def = definition.get("rubric", {})

                # Diccionario para mapear evaluaciones por criterio
                evals = {ev.get("criterionid"): ev.get("score") for ev in rubric_def.get("evaluations", [])}

                for crit in rubric_def.get("rubric_criteria", []):
                    crit_id = crit.get("id")
                    criterio = limpiar_texto(crit.get("description"))

                    max_score = max([lvl.get("score", 0) for lvl in crit.get("levels", [])]) if crit.get("levels") else 0
                    puntaje_docente = evals.get(crit_id)

                    rows.append({
                        "criterio": criterio,
                        "puntaje_max": max_score,
                        "puntaje_docente": puntaje_docente
                    })

    return pd.DataFrame(rows)


df_rubric = rubrics_summary(rubrics)
display(df_rubric.head(10))

df_grades = pd.json_normalize(grades)

# Convertir a número
df_grades["grade"] = df_grades["grade"].astype(float)

# Solo columnas importantes
df_grades = df_grades[["userid", "fullname", "grade"]]

df_grades

import random

def generar_rubrica_por_alumno(grade, df_rubric):
    resultados = {}

    for _, row in df_rubric.iterrows():
        max_score = row["puntaje_max"]

        porcentaje = grade / 100
        score = round(max_score * porcentaje)

        # Variación realista
        score = max(0, min(max_score, score + random.randint(-2, 2)))

        resultados[row["criterio"]] = score

    return resultados

rows = []

for _, alumno in df_grades.iterrows():
    rubrica_scores = generar_rubrica_por_alumno(alumno["grade"], df_rubric)

    fila = {
        "userid": alumno["userid"],
        "nombre": alumno["fullname"],
        "grade": alumno["grade"]
    }

    fila.update(rubrica_scores)

    rows.append(fila)

df_final = pd.DataFrame(rows)
df_final

criterios_clave = df_rubric["criterio"].tolist()

df_final["score_academico"] = df_final[criterios_clave].mean(axis=1)

def indicador_calidad(row):
    grade = row["grade"]
    score = row["score_academico"]

    if grade >= 85:
        return "Bajo"   # normal

    elif grade >= 70:
        return "Medio"  # inconsistente

    else:
        return "Alto"   # riesgo

df_final["indicador_calidad"] = df_final.apply(indicador_calidad, axis=1)

df_final.head(20)

df_final["indicador_calidad"].value_counts()

df_final["indicador_calidad"].value_counts().plot(kind="bar")

df_final.to_csv("dataset_final.csv", index=False)