# -*- coding: utf-8 -*-
"""TonoEnForos/mensajes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuF8O8q6U2ZzuYUu_lkD1yHP0KfaxN7R
"""

# =========================
# 1. CONFIGURACIÓN
# =========================

MOODLE_URL = "http://moodle-2025-2.lerdo.tecnm.mx/moodle/webservice/rest/server.php"
MOODLE_TOKEN = "9238b326cd606cf2b57eba793567a740"
MOODLE_COURSE_ID = 180

# Salidas
BASE_OUTDIR = "/content/data_mindguard_foros"
RAW_OUTDIR = f"{BASE_OUTDIR}/raw/moodle_forums"
PROCESSED_OUTDIR = f"{BASE_OUTDIR}/processed"

# =========================
# 2. LIBRERÍAS
# =========================
import os
import re
import json
import time
import html
import requests
import pandas as pd
from pathlib import Path
from typing import Any, Dict, List

# =========================
# 3. CREAR DIRECTORIOS
# =========================
Path(RAW_OUTDIR).mkdir(parents=True, exist_ok=True)
Path(f"{RAW_OUTDIR}/discussion_posts").mkdir(parents=True, exist_ok=True)
Path(PROCESSED_OUTDIR).mkdir(parents=True, exist_ok=True)

# =========================
# 4. SESIÓN HTTP
# =========================
session = requests.Session()
session.headers.update({"User-Agent": "moodle-forum-ingest-colab/1.0"})

# =========================
# 5. FUNCIÓN BASE PARA MOODLE
# =========================
def call(wsfunction: str, **params: Any) -> Any:
    payload = {
        "wstoken": MOODLE_TOKEN,
        "wsfunction": wsfunction,
        "moodlewsrestformat": "json",
    }
    payload.update(params)

    r = session.get(MOODLE_URL, params=payload, timeout=60)
    r.raise_for_status()
    data = r.json()

    if isinstance(data, dict) and data.get("exception"):
        raise RuntimeError(
            f"Error WS [{wsfunction}] {data.get('errorcode')}: {data.get('message')}"
        )

    return data

# =========================
# 6. HELPERS
# =========================
_TAG_RE = re.compile(r"<[^>]+>")

def clean_html(text: Any) -> str:
    if text is None:
        return ""
    s = html.unescape(str(text))
    s = _TAG_RE.sub("", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def dump_json(path: str, obj: Any) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)

def extract_forum_ids_from_contents(contents: Any) -> List[int]:
    forum_ids = []

    if not isinstance(contents, list):
        return forum_ids

    for section in contents:
        if not isinstance(section, dict):
            continue

        for module in section.get("modules", []) or []:
            if (
                isinstance(module, dict)
                and module.get("modname") == "forum"
                and "instance" in module
            ):
                try:
                    forum_ids.append(int(module["instance"]))
                except Exception:
                    pass

    return sorted(set(forum_ids))

def unix_to_iso(ts: Any) -> str | None:
    try:
        if ts is None or ts == "":
            return None
        return pd.to_datetime(int(ts), unit="s", errors="coerce").isoformat()
    except Exception:
        return None

# =========================
# 7. VERIFICAR CONEXIÓN
# =========================
site_info = call("core_webservice_get_site_info")
print("Conectado como:", site_info.get("fullname"))

# =========================
# 8. EXTRAER CONTENIDOS DEL CURSO Y DETECTAR FOROS
# =========================
contents = call("core_course_get_contents", courseid=MOODLE_COURSE_ID)
dump_json(f"{RAW_OUTDIR}/course_{MOODLE_COURSE_ID}_contents.json", contents)

forum_ids = extract_forum_ids_from_contents(contents)
dump_json(
    f"{RAW_OUTDIR}/course_{MOODLE_COURSE_ID}_forum_ids.json",
    {"courseid": MOODLE_COURSE_ID, "forumids": forum_ids},
)

print("Foros detectados:", len(forum_ids))
print("IDs:", forum_ids)

# =========================
# 9. EXTRAER DISCUSIONES POR FORO
# =========================
all_discussion_rows = []
all_discussion_ids = []

for forum_id in forum_ids:
    forum_dir = f"{RAW_OUTDIR}/forum_{forum_id}"
    Path(forum_dir).mkdir(parents=True, exist_ok=True)

    try:
        discussions_data = call("mod_forum_get_forum_discussions", forumid=forum_id)
        dump_json(f"{forum_dir}/discussions.json", discussions_data)

        discussions = discussions_data.get("discussions", []) if isinstance(discussions_data, dict) else []

        for d in discussions:
            discussion_id = d.get("discussion", d.get("id"))
            if discussion_id is None:
                continue

            all_discussion_ids.append(int(discussion_id))
            all_discussion_rows.append({
                "forum_id": forum_id,
                "discussion_id": int(discussion_id),
                "discussion_name": d.get("name"),
                "user_id": d.get("userid"),
                "groupid": d.get("groupid"),
                "timemodified": d.get("timemodified"),
            })

    except Exception as e:
        print(f"Error extrayendo discusiones del foro {forum_id}: {e}")

    time.sleep(0.15)

all_discussion_ids = sorted(set(all_discussion_ids))
discussions_df = pd.DataFrame(all_discussion_rows)
discussions_df.to_csv(f"{PROCESSED_OUTDIR}/discussions.csv", index=False, encoding="utf-8-sig")

print("Discusiones totales:", len(all_discussion_ids))

# =========================
# 10. EXTRAER POSTS POR DISCUSIÓN
# =========================
posts_raw_records = []
posts_ok = 0
posts_failed = 0
failed_discussions = []

for discussion_id in all_discussion_ids:
    try:
        posts_data = call("mod_forum_get_discussion_posts", discussionid=discussion_id)

        dump_json(
            f"{RAW_OUTDIR}/discussion_posts/discussion_{discussion_id}_posts.json",
            posts_data
        )

        posts = posts_data.get("posts", []) if isinstance(posts_data, dict) else []

        forum_id_root = posts_data.get("forumid")
        course_id_root = posts_data.get("courseid")
        discussion_id_root = posts_data.get("discussionid", discussion_id)

        for p in posts:
            author = p.get("author") if isinstance(p.get("author"), dict) else {}

            message_raw = p.get("message", "")
            message = clean_html(message_raw)

            posts_raw_records.append({
                "post_id": p.get("id"),
                "discussion_id": p.get("discussionid", discussion_id_root),
                "forum_id": forum_id_root,
                "course_id": course_id_root,
                "parent_id": p.get("parentid"),
                "user_id": author.get("id"),
                "author": author.get("fullname", ""),
                "subject": p.get("subject", ""),
                "message_raw": str(message_raw) if message_raw is not None else "",
                "message": message,
                "message_clean": message.lower(),
                "timecreated": p.get("timecreated"),
                "timemodified": p.get("timemodified"),
                "timestamp_iso": unix_to_iso(p.get("timecreated")),
                "wordcount": p.get("wordcount"),
                "charcount": p.get("charcount"),
                "hasparent": p.get("hasparent"),
                "isdeleted": p.get("isdeleted"),
                "isprivatereply": p.get("isprivatereply"),
            })

        posts_ok += 1

    except Exception as e:
        print(f"Error extrayendo posts de discusión {discussion_id}: {e}")
        posts_failed += 1
        failed_discussions.append(discussion_id)

    time.sleep(0.15)

posts_df = pd.DataFrame(posts_raw_records)
posts_df.to_csv(f"{PROCESSED_OUTDIR}/forum_messages_dataset.csv", index=False, encoding="utf-8-sig")

summary = {
    "courseid": MOODLE_COURSE_ID,
    "forums": len(forum_ids),
    "discussions_total": len(all_discussion_ids),
    "discussion_posts_files_written": posts_ok,
    "discussion_posts_failed": posts_failed,
    "failed_discussion_ids": failed_discussions,
    "rows_messages": len(posts_df),
    "outdir": BASE_OUTDIR,
}
dump_json(f"{RAW_OUTDIR}/course_{MOODLE_COURSE_ID}_summary.json", summary)

print("Mensajes extraídos:", len(posts_df))

# =========================
# 11. CONSTRUIR PAYLOADS PARA MINDGUARD
# =========================
# Se construye un JSON listo para enviar a /api/v1/analyze
# con el esquema:
# {
#   "message": "...",
#   "user_id": "...",
#   "channel": "moodle_forum",
#   "timestamp": "2026-03-31T12:00:00"
# }

payloads = []

if not posts_df.empty:
    for _, row in posts_df.iterrows():
        mensaje = row.get("message", "")
        if not isinstance(mensaje, str):
            mensaje = ""
        mensaje = mensaje.strip()

        # Omitir mensajes vacíos
        if not mensaje:
            continue

        payload = {
            "message": mensaje,
            "user_id": str(row["user_id"]) if pd.notnull(row["user_id"]) else None,
            "channel": "moodle_forum",
            "timestamp": row["timestamp_iso"] if pd.notnull(row["timestamp_iso"]) else None
        }

        payloads.append(payload)

# Guardar JSON array
payload_json_path = f"{PROCESSED_OUTDIR}/mindguard_payloads.json"
dump_json(payload_json_path, payloads)

# Guardar JSONL opcional
payload_jsonl_path = f"{PROCESSED_OUTDIR}/mindguard_payloads.jsonl"
with open(payload_jsonl_path, "w", encoding="utf-8") as f:
    for item in payloads:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("Payloads listos para API:", len(payloads))
print("JSON :", payload_json_path)
print("JSONL:", payload_jsonl_path)

# =========================
# 12. VISTA PREVIA
# =========================
payloads_df = pd.DataFrame(payloads)
print("\nVista previa de payloads:")
display(payloads_df.head(20))

# =========================
# 13. OPCIONAL: EJEMPLO DE ENVÍO A MINDGUARD
# =========================
# DESACTIVADO por defecto.
# Solo úsalo si ya tienes tu API local activa y la API key correcta.

ENVIAR_A_API = False

MINDGUARD_API_URL = "http://127.0.0.1:8000/api/v1/analyze"
MINDGUARD_API_KEY = "PEGA_AQUI_TU_API_KEY_REAL"

if ENVIAR_A_API:
    headers = {
        "Content-Type": "application/json",
        "x-api-key": MINDGUARD_API_KEY
    }

    resultados = []

    for payload in payloads:
        try:
            r = requests.post(MINDGUARD_API_URL, json=payload, headers=headers, timeout=60)
            respuesta = r.json() if r.headers.get("content-type", "").startswith("application/json") else {"raw": r.text}

            resultados.append({
                "user_id": payload.get("user_id"),
                "timestamp": payload.get("timestamp"),
                "message": payload.get("message"),
                "status_code": r.status_code,
                "response": respuesta
            })
        except Exception as e:
            resultados.append({
                "user_id": payload.get("user_id"),
                "timestamp": payload.get("timestamp"),
                "message": payload.get("message"),
                "status_code": None,
                "response": {"error": str(e)}
            })

        time.sleep(0.05)

    resultados_path = f"{PROCESSED_OUTDIR}/mindguard_results.json"
    dump_json(resultados_path, resultados)

    print("Resultados guardados en:", resultados_path)